### ISSUE TITLE
Timer Issues

### ISSUE THREAD

**Issue by pasieng** [PayneWheat/risk#79]
I created a 30 second timer, but there are two issues. 
1. I don't know how to automatically terminate the showInputDialog box if the current player does not make an action within 30 seconds. 
2.  I also don't know how we should give the next player their turn if the current player does not make an action within 30 seconds.

**Comment by pasieng** [comment]
If a Player runs out of time to make an action, I can only think of current Player manually terminating the showInputDialog box by clicking the 'X' icon. They can attempt to put an input after the time limit, but it wouldn't be recorded. Instead, the game moves on to the next Player (which is something we need to figure out).

**Comment by PayneWheat** [comment]
Resolved the problem with Swing. There's a dispose() method to close the parent window.

I needed to code some specific cases into the board and player methods responsible for input. Like, if the user doesn't pick a territory while selecting where to put their armies at the beginning of their turn, the armies must go somewhere in order to move the game along. So I coded it to randomly choose a player's territory and put all of their available armies on it.

There were a couple other edge cases for when the user doesn't supply input, but I figured out a way to make them all work.

We still need to do something similar for input from drop-down boxes or from Yes/No dialog boxes. I'll get around to that soon.
